In [2]:
# numpy 로딩
import numpy as np

In [4]:
# 1차원 numpy 배열
list1 = [1,2,3,4,5]
list1

[1, 2, 3, 4, 5]

In [5]:
# 넘파이배열로 변환
arr = np.array(list1)
arr

array([1, 2, 3, 4, 5])

In [6]:
print(list1)
print(arr)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [7]:
arr2 = np.array((5,6,7,8,9,10))
arr2

array([ 5,  6,  7,  8,  9, 10])

In [8]:
# 2차원 배열 생성
arr3 = np.array([[1,2,3],[4,5,6]])
arr3

array([[1, 2, 3],
       [4, 5, 6]])

배열의 크기 :   
배열명.shape

In [11]:
# 앞 숫자: 데이터 수(행) 뒷숫자: 특성 수 (열)
# 1차원 배열은 행으로 저장 (세로) 5 6 7 ...
arr3.shape, arr2.shape

((2, 3), (6,))

배열의 값의 개수 :   
배열명.size

In [12]:
arr3.size

6

배열에 저장된 데이터 타입:   

배열명.dtype

In [13]:
# 4 byte
print(arr3.dtype)

int32


In [15]:
arr4 = np.array([2.3, 1.3, 3.4, 4.5])
print(arr4.dtype)

float64


배열의 차원수  
배열명.ndim

In [16]:
print(arr2.ndim)
print(arr3.ndim)

1
2


# 배열 초기화 함수

- 배열명.zeros(행, 열):(행,열) 배열에 0으로 초기화
- 배열명.ones(행, 열):(행,열) 배열에 1로 초기화

In [18]:
arr4 = np.zeros((2,2))

arr4

array([[0., 0.],
       [0., 0.]])

In [19]:
arr5 = np.ones((3,4))

arr5

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

- np.full((행,열),값) : (행,열) 배열에 값으로 초기화

In [20]:
arr6 = np.full((3,4),7)

arr6

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [6]:
arr7 = np.full((5,7),3)

arr7

array([[3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3]])

np.arange(시작값, 끝값+1, 증가값)

In [9]:
arr8 = np.arange(1, 11, 1)

arr8

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr9 = np.arange(1, 7, 1)

arr9

array([1, 2, 3, 4, 5, 6])

데이터 타입을 설정해서 배열을 설정: dtype 파라미터

In [11]:
# 실수형 8파이트
arr10 = np.array([1,2,3,4], dtype = np.float64)
arr10

array([1., 2., 3., 4.])

In [12]:
arr10.dtype

dtype('float64')

생성된 데이터의 자료형을 변경하고 싶다면 -> astype()

배열명.astype("타입종류")

In [13]:
arr10 = arr10.astype("int32")

arr10.dtype

dtype('int32')

임의의 값으로 배열 생성

In [14]:
# 1에서 6 사이 임의 값
np.random.randint(1, 6)

4

In [15]:
# np.random.rand(행, 열)

# 0과 1사이 임의의 실수으로 배열 생성
np.random.rand(2, 3)

array([[0.73171854, 0.96923573, 0.05729831],
       [0.55927008, 0.06433504, 0.97769389]])

In [17]:
# size = 배열 크기
np.random.randint(1, 6+1, size=(2,2))

array([[3, 1],
       [6, 1]])

In [32]:
# np.random.randint(1, 45+1, size=(1,6))

lottoN = []
while True: 
    if len(lottoN) == 6 :
        break
        
    n = np.random.randint(1, 8)
    if len(lottoN) == 0 :
        lottoN.append(n)
    else :
        check = 0
        for num in lottoN :
            if num == n :
                check = 1
                break
        
        if check == 0 :
            lottoN.append(n)

lottoN.sort()

lottoN

[1, 2, 3, 4, 6, 7]

In [45]:
lottoNum = []

num = np.random.randint(1,45)

for i in range(6) : # 6번 반복
    while num in lottoNum : # 그 숫자가 있으면 true니까
        num = np.random.randint(1,45)
    lottoNum.append(num)
    
lottoNum.sort()

lottoNum

[2, 5, 16, 37, 39, 42]

배열명.reshape(행, 열)

In [64]:
arr12 = np.ones((3,4))
arr12.shape

(3, 4)

In [48]:
arr12 = arr12.reshape(2, 6)
arr12

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [50]:
# 개수가 맞아야함
arr12 = arr12.reshape(4, 6)
arr12

ValueError: cannot reshape array of size 12 into shape (4,6)

In [51]:
# -1은 행의 크기를 열에 크기에 따라 결정
arr12 = arr12.reshape(-1, 3)
arr12

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [65]:
arr12 = arr12.reshape(2, -1)
arr12

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

flatten(): 배열을 1차원으로 변환

In [66]:
arr12.shape

(2, 6)

In [67]:
arr12 = arr12.flatten()

arr12.shape

(12,)

In [59]:
# 산술연산
arr13 = np.array([2,4,6])
arr14 = np.array([4,2,3])

arr13 + arr14

array([6, 6, 9])

In [68]:
arr13 * arr14

array([ 8,  8, 18])

2개의 넘배열을 사칙연산하는 함수를 작성
- 연산자도 파라미터로 할당  
calMetrix(arr1, arr2, "+")

In [74]:
arr13 = np.array([2,4,6])
arr14 = np.array([4,2,3])

def celMetrix(arr1, arr2, cal_str) :
    if cal_str == "+" :
        return arr1 + arr2
    elif cal_str == "-" :
        return arr1 - arr2
    elif cal_str == "*" :
        return arr1 * arr2
    elif cal_str == "/" :
        return arr1 / arr2
    
rslt = celMetrix(arr13,arr14,"/")
print(rslt)

[0.5 2.  2. ]


인덱싱과 슬라이싱

In [4]:
arr20 = np.array([[3,4,6,8],
                [6,7,4,9],
                [1,4,3,9],
                 [9,2,4,1]])

arr20

array([[3, 4, 6, 8],
       [6, 7, 4, 9],
       [1, 4, 3, 9],
       [9, 2, 4, 1]])

In [5]:
arr20[2]

array([1, 4, 3, 9])

In [6]:
arr20[2][3]

9

In [7]:
arr21 = arr20.flatten()
arr21.shape

(16,)

In [8]:
arr21

array([3, 4, 6, 8, 6, 7, 4, 9, 1, 4, 3, 9, 9, 2, 4, 1])

In [9]:
arr21[:5]

array([3, 4, 6, 8, 6])

In [10]:
arr21[-4:]

array([9, 2, 4, 1])

In [12]:
arr22 = np.array([1,2,3,4,5])

arr22

array([1, 2, 3, 4, 5])

In [13]:
arr22[0:2] = 10

arr22

array([10, 10,  3,  4,  5])

In [14]:
arr22[3:] = 20

arr22

array([10, 10,  3, 20, 20])

In [15]:
arr20 = np.array([[3,4,6,8],
                [6,7,4,9],
                [1,4,3,9],
                 [9,2,4,1]])

arr20

array([[3, 4, 6, 8],
       [6, 7, 4, 9],
       [1, 4, 3, 9],
       [9, 2, 4, 1]])

2차원 배열의 슬라이싱  
배열명[행의시작인덱스:행의끝인덱스+1, 열의시작인덱스:열의끝인덱스+1]

In [16]:
arr20[:2, :2]

array([[3, 4],
       [6, 7]])

In [21]:
arr20[1:, 1:3]

array([[7, 4],
       [4, 3],
       [2, 4]])

In [23]:
arr20[1:, 1]

array([7, 4, 2])

In [24]:
arr20[3, 1:]

array([2, 4, 1])

In [25]:
arr20[0, 3]

8

In [27]:
arr20[3, 3]

1

boolean 인덱싱 (중요)

- 조건에 맞는 값만 표시하거나 가져오는것

In [31]:
arr23 = np.array([12, 40, 22, 33, 23])

In [32]:
arr23 > 20

array([False,  True,  True,  True,  True])

In [33]:
arr23[arr23 > 20]

array([40, 22, 33, 23])

In [34]:
arr23[arr23%2 == 0]

array([12, 40, 22])

arr23에서 짝수인 값을 0으로 변경

In [37]:
arr23[arr23%2 == 0] = 0

arr23

array([ 0,  0,  0, 33, 23])

In [39]:
arr23 = np.array([12, 40, 22, 33, 23])

arr23[arr23 > 20] = 100

arr23

array([ 12, 100, 100, 100, 100])

범용함수

In [40]:
arr23 = np.array([12, 40, 22, 33, 23])

In [41]:
print(arr23.sum())
print(np.sum(arr23))

130
130


In [42]:
print(arr23.mean())
print(np.mean(arr23))

26.0
26.0


In [43]:
print(np.sqrt(arr23))

[3.46410162 6.32455532 4.69041576 5.74456265 4.79583152]


In [45]:
# delimiter = "," : ,를 제거하고 데이터를 부름
data = np.loadtxt("height_weight.txt", delimiter = ",")

data

array([[175.2, 180.3, 175. , 169.2, 185.2, 188. , 177.6, 178.2, 177. ,
        179. ],
       [ 65.6,  88. ,  79.2,  69.3,  55. ,  71.2,  73. ,  68.9,  74. ,
         82. ]])

In [46]:
print(data.shape)

(2, 10)


In [53]:
height = data[0]
weight = data[1]

print(height)
print(weight)

bmi = (weight / (height*height)) * 100

np.round(bmi,2)

[175.2 180.3 175.  169.2 185.2 188.  177.6 178.2 177.  179. ]
[65.6 88.  79.2 69.3 55.  71.2 73.  68.9 74.  82. ]


array([0.21, 0.27, 0.26, 0.24, 0.16, 0.2 , 0.23, 0.22, 0.24, 0.26])